#include <string>
#include <optional>

class ParkingTicket;

enum Color 
{
  RED, ORANGE, YELLOW, GREEN, BLUE, PURPLE, BLACK, WHITE, TAN,
};

class ParkedCar
{
  std::string make_m, model_m, license_num_m;
  Color color_m;
  unsigned mins_parked_m;
public:
  /// Longest license plate in USA is 8
  constexpr static std::string INVALID_PLATE { "INVALID_PLATE" };

  ParkedCar(
      std::string make, std::string model, Color color, 
      std::string license_num, unsigned minutes_parked);

  inline std::string getMake() const 
  { return make_m; }

  inline std::string getModel() const
  { return model_m; }

  inline std::string getLicenseNum() const
  { return license_num_m; }

  inline Color getColor() const
  { return color_m; }

  inline unsigned getMinutesParked() const
  { return mins_parked_m; }

  inline void setMinutesParked(unsigned mins)
  { mins_parked_m = mins; }

  ParkedCar& operator++();

  ParkedCar operator++(int);
};

class ParkingMeter
{
  unsigned mins_bought_m;
public:
  explicit inline ParkingMeter(unsigned mins = 30): mins_bought_m(mins) {}

  inline unsigned getMinutesPurchased(void) const 
  { return mins_bought_m; }

  inline void setMinutesPurchased(unsigned mins) 
  { mins_bought_m = mins; }
};

class PoliceOfficer 
{
  std::string name_m;
  unsigned badge_num_m;
public:
  inline PoliceOfficer(std::string name, unsigned badge_num):
    name_m(name), badge_num_m(badge_num) {}

  inline unsigned getBadgeNum() const
  { return badge_num_m; }

  std::string getName() const 
  { return name_m; }

  /// returns an optional containing a ParkingTicket if the car needs to be 
  /// ticketed, otherwise an empty optional is returned.
  std::optional<ParkingTicket> inspectParking(
      ParkedCar &car, ParkingMeter &meter);
};

class ParkingTicket 
{
  ParkedCar ticketed_m;
  ParkingMeter meter_m;
  PoliceOfficer popo_m;
public:
  ParkingTicket(ParkedCar &ticketed, ParkingMeter &meter, PoliceOfficer &popo); 

  /// Generates a report which contains the following formatted data
  /// Make: 
  /// Model:
  /// Color:
  /// License Number:
  /// Minutes Parked:
  /// Minutes Purchased:
  /// Fine:
  /// Officer Name:
  /// Officer Badge Number:
  std::string report() const;

  /// Displays a ParkingTicket to ostream using the report format generated by
  /// the ParkingTicket::report() function.
  friend std::ostream& operator<<(
      std::ostream &ostream, const ParkingTicket &ticket);
private:
  unsigned getFine() const;
};
