#include <string>
#include <optional>

class ParkingTicket;

/// commonly used paint colors for cars
enum Color 
{
  RED, ORANGE, YELLOW, GREEN, BLUE,
  PURPLE, BLACK, WHITE, TAN,
};

class ParkedCar
{
  std::string make_m, model_m, license_num_m;
  Color color_m;
  unsigned mins_parked_m;
public:
  /// Longest license plate in USA is 8
  constexpr static std::string INVALID_PLATE { "INVALID_PLATE" };

  /// string make : the car manufacturer, i.e. lexus, ford, mercedes.
  /// string model : the car model, i.e. ford focus.
  /// Color color : all caps car color, i.e RED, BLUE, YELLOW, ORANGE.
  /// string license_num : an 8 character string max license plate value
  /// unsigned minutes_parked : the number of minutes the car has been parked
  ///
  /// Returns a ParkedCar object.
  ParkedCar(
      std::string make, std::string model, Color color, 
      std::string license_num, unsigned minutes_parked);

  /// returns the make of the car
  inline std::string getMake() const 
  { return make_m; }

  /// returns the model of the car
  inline std::string getModel() const
  { return model_m; }

  /// returns the license plate number of the car
  inline std::string getLicenseNum() const
  { return license_num_m; }

  /// returns the color of the car in string format
  std::string getColor() const;

  /// returns the number of minutes the car has been parked
  inline unsigned getMinutesParked() const
  { return mins_parked_m; }

  /// sets the number of minutes the car has been parked
  inline void setMinutesParked(unsigned mins)
  { mins_parked_m = mins; }
};

class ParkingMeter
{
  unsigned mins_bought_m;
public:
  /// unsigned mins : the number of minutes of parking time purchased.
  ///
  /// Returns a ParkingMeter object. Default number of minutes bought, 30m.
  explicit inline ParkingMeter(unsigned mins = 30): mins_bought_m(mins) {}

  /// returns the number of minutes of parking time purchased
  inline unsigned getMinutesPurchased(void) const 
  { return mins_bought_m; }

  /// sets the number of minutes of parking time purchased
  inline void setMinutesPurchased(unsigned mins) 
  { mins_bought_m = mins; }
};

class PoliceOfficer 
{
  std::string name_m;
  unsigned badge_num_m;
public:
  /// string name : the name of the police officer
  /// unsigned badge_num : the badge number of the police officer
  ///
  /// returns a police officer object
  inline PoliceOfficer(std::string name, unsigned badge_num):
    name_m(name), badge_num_m(badge_num) {}

  /// returns the officers badge number
  inline unsigned getBadgeNum() const
  { return badge_num_m; }

  /// returns the officers name
  std::string getName() const 
  { return name_m; }

  /// ParkedCar &car : the parked car object being inspected for legality in
  /// terms of how long it has been parked.
  /// ParkingMeter &meter : the meter being checked for number of minutes of
  /// purchased.
  ///
  /// returns an optional containing a ParkingTicket if the car needs to be 
  /// ticketed, otherwise an empty optional is returned. Optional should be 
  /// checked before attempting use {*,->}, otherwise causes undefined behavior.
  std::optional<ParkingTicket> inspectParking(
      ParkedCar &car, ParkingMeter &meter);
};

class ParkingTicket 
{
  ParkedCar ticketed_m;
  ParkingMeter meter_m;
  PoliceOfficer police_m;
public:
  /// ParkedCar &ticketed : the parked car being ticketed
  /// ParkingMeter &meter : the meter referenced to determine the ticket is
  /// needed
  /// PoliceOfficer &police : the police officer issuing the ticket
  ///
  /// returns a parking ticket object.
  ParkingTicket(ParkedCar &ticketed, ParkingMeter &meter, PoliceOfficer &police); 

  /// Generates a report which contains the following formatted data
  /// Make: 
  /// Model:
  /// Color:
  /// License Number:
  /// Minutes Parked:
  /// Minutes Purchased:
  /// Fine:
  /// Officer Name:
  /// Officer Badge Number:
  ///
  /// The report is returned as a string.
  std::string report() const;

  /// std::ostream ostream : the ostream inserted into
  /// const ParkingTicket &ticket : the ticket which is being displayed on
  /// ostream.
  ///
  /// Displays a ParkingTicket to ostream using the report format generated by
  /// the ParkingTicket::report() function.
  friend std::ostream& operator<<(
      std::ostream &ostream, const ParkingTicket &ticket);

  /// returns a fine based on the number of minutes in violation of parking
  /// rules
  int getFine() const;

  /// returns a fine based on the number of minutes in violation of parking
  /// rules
  static int getFine(unsigned mins_parked, unsigned mins_bought);
};
