#include <string>
#include <optional>

class ParkingTicket;

enum Color 
{
  RED, ORANGE, YELLOW, GREEN, BLUE, PURPLE, BLACK, WHITE, TAN,
};

class ParkedCar
{
  std::string make_m, model_m;
  Color color_m;
  unsigned license_num_m;
  unsigned minutes_parked_m;
public:
  ParkedCar(
      std::string make, std::string model, Color color, 
      unsigned license_num, unsigned minutes_parked);

  inline std::string getMake() const 
  { return make_m; }

  inline std::string getModel() const
  { return model_m; }

  inline Color getColor() const
  { return color_m; }

  inline unsigned getLicenseNum() const
  { return license_num_m; }

  inline unsigned getMinutedParked() const
  { return minutes_parked_m; }

  inline void setMinutesParked(unsigned minutes)
  { minutes_parked_m = minutes; }

  ParkedCar& operator++();

  ParkedCar operator++(int);
};

class ParkingMeter
{
  unsigned minutes_purchased_m;
public:
  explicit inline ParkingMeter(unsigned mins = 30):
    minutes_purchased_m(mins) 
  {};

  inline unsigned getMinutesPurchased(void) 
  { return minutes_purchased_m; }

  inline void setMinutesPurchased(unsigned mins) 
  { minutes_purchased_m = mins; }
};

class PoliceOfficer 
{
  std::string name_m;
  unsigned badge_num_m;
public:
  inline PoliceOfficer(std::string name, unsigned badge_num):
    name_m(name), badge_num_m(badge_num)
  {};

  inline unsigned getBadgeNum() const
  { return badge_num_m; }

  std::string getName() const 
  { return name_m; }

  /// returns an optional containing a ParkingTicket if the car needs to be 
  /// ticketed, otherwise an empty optional is returned.
  std::optional<ParkingTicket> inspectParking(
      ParkedCar &car, ParkingMeter &meter);
private:
  /// returns true if a Car is violating the parking laws.
  static bool isViolating(ParkedCar &car, ParkingMeter &meter);
};

class ParkingTicket 
{
  ParkedCar ticketed_m;
  ParkingMeter meter_m;
  PoliceOfficer popo_m;
public:
  ParkingTicket(ParkedCar &ticketed, ParkingMeter &meter, PoliceOfficer &popo); 

  /// Generates a report which contains the following formatted data
  /// Make: 
  /// Model:
  /// Color:
  /// License Number:
  /// Minutes Parked:
  /// Minutes Purchased:
  /// Fine:
  /// Officer Name:
  /// Officer Badge Number:
  std::string report() const;

  /// Displays a ParkingTicket to ostream using the report format generated by
  /// the ParkingTicket::report() function.
  friend std::ostream& operator<<(
      std::ostream &ostream, ParkingTicket const &ticket);
private:
  unsigned getFine() const;
};
